### ISSUE TITLE
unknown target: main

### ISSUE THREAD

**Issue by ianatarewe** [troykinsella/concourse-fly-resource#18]
Can you clarify in the readme whether the resource logs in by itself or if we need to log in ourselves. It does not seem to create a target, which AFAIK is done on initial login.

resource:
```
- name: admin-fly
  type: fly
  source:
    url: my.server.duckdns.org
    username: ((concourse_admin_username))
    password: ((concourse_admin_password))
    team: main
```

put:

```
  # Apply user configs
  - put: admin-fly
    inputs: all
    params:
      options: set-team -n initial-pipeline-team -c initial-concourse/teams/initial-pipeline-team.yml 
```
