### ISSUE TITLE
Run against current team?

### ISSUE THREAD

**Issue by cjohansen** [troykinsella/concourse-fly-resource#6]
I want to use this resource to create self-updating pipelines that might run under multiple teams. It would be very helpful if I could use fly against the current team (`$BUILD_PIPELINE_NAME` in the resource implementation). I'm guessing that changing the default is undesired as it would break backwards compatibility. Would you consider a pull request to do something like this?

```yml
- name: fly
  type: fly
  source:
    url: ((concourse_url))
    username: ((concourse_user))
    password: ((concourse_password))
    use_current_team: true
```
